# Generated by Django 3.0.8 on 2020-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.wired.com%2Fstory%2Fcats-australia-bushfires%2F&psig=AOvVaw0dcvs9cBr93XtPoiVwHnVo&ust=1596340320650000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPitg6CN-eoCFQAAAAAdAAAAABAD'),
        ),
    ]
