# Generated by Django 3.0.8 on 2020-08-10 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200805_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
